### ISSUE TITLE
fatal error with multi-tenant plugin

### ISSUE THREAD

**Issue by ibotty** [openshift/openshift-sdn#291]
See this [fpaste](https://paste.fedoraproject.org/354655/46046660/) for the backtrace.

The first few lines are inlined below.

```
fatal error: concurrent map read and map write
goroutine 470 [running]:
runtime.throw(0x38e04e0, 0x21)
/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc821789920 sp=0xc821789908
runtime.mapaccess2_faststr(0x2823780, 0xc8207bd4a0, 0xc8211fa9f8, 0x8, 0x1, 0x1)
/usr/local/go/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc821789980 sp=0xc821789920
github.com/openshift/openshift-sdn/plugins/osdn.(*Registry).OnEndpointsUpdate(0xc820652cd0, 0xc821b92000, 0x19, 0x25)
/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/registry.go:692 +0x74a fp=0xc821789e40 sp=0xc821789980
k8s.io/kubernetes/pkg/proxy/config.(*EndpointsConfig).RegisterHandler.func1(0x27c4cc0, 0xc820b2b6c0)
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/proxy/config/config.go:100 +0xdc fp=0xc821789ea0 sp=0xc821789e40
k8s.io/kubernetes/pkg/util/config.ListenerFunc.OnUpdate(0xc82090fda0, 0x27c4cc0, 0xc820b2b6c0)
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/config/config.go:110 +0x30 fp=0xc821789eb8 sp=0xc821789ea0
k8s.io/kubernetes/pkg/util/config.(*Broadcaster).Notify(0xc8206bb5c0, 0x27c4cc0, 0xc820b2b6c0)
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/config/config.go:138 +0xf8 fp=0xc821789f40 sp=0xc821789eb8
k8s.io/kubernetes/pkg/proxy/config.watchForUpdates(0xc8206bb5c0, 0x7f53a4922cc8, 0xc8206bb470, 0xc8209c4d80)
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/proxy/config/config.go:297 +0x76 fp=0xc821789f70 sp=0xc821789f40
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc821789f78 sp=0xc821789f70
created by k8s.io/kubernetes/pkg/proxy/config.NewEndpointsConfig
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/proxy/config/config.go:93 +0x248
```

**Comment by smarterclayton** [comment]
Go 1.6 started throwing this error, but it was a possibility before.

**Comment by smarterclayton** [comment]
This means we have a race in this code that has to be addressed.
